# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
